name: Build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: |
          set -ex
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Build Alpine container
        run: |
          set -ex
          podman build -t ghcr.io/charles8191/hardened_malloc/artifact:alpine -f Containerfile.alpine
      - name: Build Debian container
        run: |
          set -ex
          podman build -t ghcr.io/charles8191/hardened_malloc/artifact:debian -f Containerfile.debian
      - name: Build binary using Alpine
        run: |
          set -ex
          mkdir out-alpine
          podman run -v ./out-alpine:/out ghcr.io/charles8191/hardened_malloc/artifact:alpine
      - name: Build binary using Debian
        run: |
          set -ex
          mkdir out-debian
          podman run -v ./out-debian:/out ghcr.io/charles8191/hardened_malloc/artifact:debian
      - name: Push binaries
        run: |
          set -ex
          cp -vf out-alpine/libhardened_malloc.so libhardened_malloc-alpine.so
          cp -vf out-debian/libhardened_malloc.so libhardened_malloc-debian.so
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add libhardened_malloc-{alpine,debian}.so
          git commit --allow-empty -m "[AUTOMATED] Upload binaries"
          git push
      - name: Push containers
        run: |
          set -ex
          podman push ghcr.io/charles8191/hardened_malloc/artifact:alpine
          podman push ghcr.io/charles8191/hardened_malloc/artifact:debian